### ISSUE TITLE
Question about CCP response

### ISSUE THREAD

**Issue by unixorn** [tlkamp/litter-api#17]
Does it report CCP when it starts waiting to rotate after the cat has used the box, or does it report when it actually starts to rotate the drum?

I ask because it'd be nice to be able to scrape that and start a fan while there's a pending rotation.

**Comment by tlkamp** [comment]
It reports `CCP` while the cycling is actually in progress, and `CST` while waiting to start a cycle. If you wanted to turn on a fan you would want to watch for `CCC` (clean cycle completed). That status is only set for a very brief period of time, I had to set my prom scrape interval to `5s` to capture it:

![image](https://github.com/tlkamp/litter-api/assets/18516698/1b65bdc6-760a-49a4-a288-39de89b14887)


The Litter Robot 3 does have an integration with [home assistant](https://www.home-assistant.io/integrations/litterrobot/) that might be better suited for this rather than Prometheus.
